# Generated by Django 5.1.1 on 2024-10-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=20)),
                ('caminho_anexo', models.CharField(max_length=50)),
                ('servidor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anexo',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=40)),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=20)),
                ('perfil', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'participante',
            },
        ),
        migrations.CreateModel(
            name='SalaAula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('instituicao', models.CharField(max_length=100)),
                ('data_aula', models.DateField(auto_now_add=True)),
                ('disciplina', models.CharField(max_length=40)),
                ('conteudo', models.TextField()),
            ],
            options={
                'db_table': 'sala_aula',
            },
        ),
    ]
