# Generated by Django 5.1.1 on 2024-10-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('data_aula', models.DateField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(max_length=1)),
                ('id_participante', models.ForeignKey(db_column='id_participante', on_delete=django.db.models.deletion.DO_NOTHING, to='core.participante')),
                ('id_sala_aula', models.ForeignKey(db_column='id_sala_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='core.salaaula')),
            ],
            options={
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='ComentarioAnexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('id_anexo', models.ForeignKey(db_column='id_anexo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.anexo')),
                ('id_comentario', models.ForeignKey(db_column='id_comentario', on_delete=django.db.models.deletion.DO_NOTHING, to='core.comentario')),
            ],
            options={
                'db_table': 'comentario_anexo',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteSalaAnexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('id_participante', models.ForeignKey(db_column='id_participante', on_delete=django.db.models.deletion.DO_NOTHING, to='core.participante')),
                ('id_sala_aula', models.ForeignKey(db_column='id_sala_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='core.salaaula')),
            ],
            options={
                'db_table': 'participante_sala_anexo',
            },
        ),
        migrations.CreateModel(
            name='SalaAulaAnexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('id_anexo', models.ForeignKey(db_column='id_anexo', on_delete=django.db.models.deletion.DO_NOTHING, to='core.anexo')),
                ('id_sala_aula', models.ForeignKey(db_column='id_sala_aula', on_delete=django.db.models.deletion.DO_NOTHING, to='core.salaaula')),
            ],
            options={
                'db_table': 'sala_aula_anexo',
            },
        ),
    ]
